<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1EKAV2N" failures="1" tests="6" name="com.selenium.trainingday10.TestNGRetryConcept" time="0.034" errors="0" timestamp="2021-05-25T17:03:00 IST" skipped="3">
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test3" time="0.002"/>
  <system-out/>
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test1" time="0.020">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test1" time="0.003">
    <failure message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false],
	expected [true] but found [false],
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.selenium.trainingday10.TestNGRetryConcept.test1(TestNGRetryConcept.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="com.selenium.trainingday10.TestNGRetryConcept" name="test2" time="0.003"/>
  <system-out/>
</testsuite> <!-- com.selenium.trainingday10.TestNGRetryConcept -->
